services:
  findpharma:
    build: .
    command: pm2-runtime ecosystem.config.js
    volumes:
      - pharmacies_geo.json:/app/pharmacies_geo.json
      - logs:/app/logs
    environment:
      - NODE_ENV=production
    
    labels:
      - traefik.enable=true
      - traefik.http.routers.findpharma.rule=Host(`findpharma.cimeit.tech`)
      - traefik.http.services.findpharma.loadbalancer.server.port=3000
      - traefik.http.routers.findpharma.tls=true
      - "traefik.http.routers.findpharma.entrypoints=websecure"
      - "traefik.http.routers.findpharma.tls.certresolver=letsencrypt"
    networks:
      - traefik
    restart: unless-stopped


volumes:
  pharmacies_geo.json:
    driver: local
  logs:
    driver: local

networks:
  traefik:
    external: true