services:
  findpharma:
    build: .
    command: /app/scripts/init.sh
    volumes:
      - logs:/app/logs
    environment:
      - NODE_ENV=production
    
    labels:
      - traefik.enable=true
      - traefik.http.routers.findpharma.rule=Host(`findpharma.cimeit.tech`)
      - traefik.http.services.findpharma.loadbalancer.server.port=3000
      - traefik.http.routers.findpharma.tls=true
      - "traefik.http.routers.findpharma.entrypoints=websecure"
      - "traefik.http.routers.findpharma.tls.certresolver=letsencrypt"
    networks:
      - traefik
    restart: unless-stopped


volumes:
  logs:
    driver: local

networks:
  traefik:
    external: true